### ISSUE TITLE
Apply managed identity approach to the metrics Function Apps

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#1055]
- [x] Only Dashboard can access metrics API (#1084 and #1092)
- [ ] Only event from Event Hub can trigger Collector
- [ ] ~Log managed identity data in Collector (see #1054)~

**Comment by kingcomma** [comment]
Event Hub identities / authentication: https://docs.microsoft.com/en-us/azure/event-grid/security-authentication and https://docs.microsoft.com/en-us/azure/event-grid/managed-service-identity

**Comment by kingcomma** [comment]
Using an HTTP trigger (webhook) for event delivery: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook

**Comment by ryanhofdotgov** [comment]
Saw [this comment ](https://github.com/18F/piipan/pull/1054#issuecomment-860882578) in #1054 and just want to clarify that the primary goal is just to ensure that only the Event Hub event can trigger the collector (e.g., can't be invoked by an unauthenticated HTTP client), but do not actually know if managed identity is the best and typical way to accomplish that.

**Comment by kingcomma** [comment]
[Service tags](https://docs.microsoft.com/en-us/azure/event-grid/network-security#service-tags) seem like a potential solution for limiting a Function to only Event Grid, but the option doesn't appear to be available in Azure Government (it's not specifically documented one way or another).

Commercial portal:

<img width="312" alt="Screen Shot 2021-06-24 at 5 05 15 PM" src="https://user-images.githubusercontent.com/3246955/123332744-e8631c80-d50e-11eb-8696-71b37157f702.png">

Government portal:

<img width="319" alt="Screen Shot 2021-06-24 at 5 05 06 PM" src="https://user-images.githubusercontent.com/3246955/123332755-ec8f3a00-d50e-11eb-9104-fbe0ce535c09.png">

**Comment by kingcomma** [comment]
With more experimenting, service tags may be usable on AzureUSGovernment. I can set an access restriction that references a service tag via the CLI with `az functionapp config access-restriction add -n ... -g ... --priority 100 --service-tag AzureEventGrid` and the rule will show up in the Portal:

<img width="321" alt="Screen Shot 2021-06-25 at 2 39 22 PM" src="https://user-images.githubusercontent.com/3246955/123470988-24f05000-d5c3-11eb-90e4-4c5a2d70d7ba.png">

**Comment by kingcomma** [comment]
@ryanhofdotgov After some research, it appears there are two primary ways to achieve the "Only event from Event Hub can trigger Collector" task:

1. At the network level, by creating an access restriction and using the AzureEventGrid [service tag](https://docs.microsoft.com/en-us/azure/virtual-network/service-tags-overview) to only allow incoming traffic from Event Grid. Similar to how we used to restrict access to our app service instances, but relying on Azure's service tags rather than a static IP range.
2. At the auth level, by assigning the Event Grid subscription a managed identity and turning on app service authentication for the Function app. Effectively the same approach we take for protecting our APIs.

(1) is the smallest lift to implement and seems like it meets our needs. Any qualms starting with that approach?

**Comment by ryanhofdotgov** [comment]
@kingcomma Sounds good – let's do #1 for now and open up a backlog item for #2 so we can ultimately have a zero trust approach throughout.
