### ISSUE TITLE
Lock down access to participant database through Azure resources that need it

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#11]
Using IaC approach in #1, establish internal network isolation for the per-state databases and the per-state ETL; see #7 and #8. Remove AllowAllWindowsAzureIps setting in the process.

**Comment by echappen** [comment]
@ryanhofdotgov I'm running into [an issue I had previously](https://github.com/18F/piipan/pull/435#issuecomment-786907159) when attempting to deploy a postgres database on a Basic tier with VNet resources:

```
"code": "FeatureNotSupportedForEdition",
"message": "This feature is not available for the selected edition 'Basic'."
```
I finally found where this is [specified in the docs](https://docs.microsoft.com/en-us/azure/postgresql/concepts-limits#vnet-service-endpoints). We may have to bump the participant-records db server up from Basic to General Purpose.

**Comment by echappen** [comment]
Adding what I found here about Azure Gov's use of VNets and Private Links:
- [Azure post](https://azure.microsoft.com/en-us/updates/privatelinkgagovcloud/) claiming private links are available to Postgres Databases in Azure Gov and have feature parity with Azure Commercial
- [General Availability](https://azure.microsoft.com/en-us/global-infrastructure/services/?products=virtual-network,private-link) of VNets and Private Links across all resources in Azure Gov
- VNets and Private Endpoints were available for creation in the FNS portal

Since this issue turned into a research spike, I'll open another issue to codify our findings into iac.
