### ISSUE TITLE
Configure Easy Auth exception for Front Door health check probe

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#1131]
Front Door health check probe will fail against dashboard/query tool when easy auth is enabled. Various blog post seem to indicate that solution is to create a page that is excluded from Easy Auth that Front Door can "ping". Awaiting FastTrack feedback.

Could be related to follow on of #1125 (see implementation notes).

**Comment by kingcomma** [comment]
After some poking around, here's what I've found:
- Resolving the failures is fairly straightforward: [Add a static file](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-5.0#serve-static-files) to the app's `wwwroot`, [exclude](https://docs.microsoft.com/en-us/azure/templates/microsoft.web/sites/config-authsettingsv2?tabs=json#globalvalidation-object) that file from the authentication paths, and [point front door](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2019-04-01/frontdoors?tabs=json#healthprobesettingsproperties-object) to that excluded path (see #1226 draft for implementation details)
- With this done, there are no more failed health probe checks in the log entries.
- However, the volume of successful health probe checks in the log entries is _even greater_. I assume this is because Front Door has a threshold for failures. Once that threshold is crossed, it considers the backend down and won't probe it for a given period of time. If the backend is healthy, there is no pause in probes and [probe volume can be very high](https://docs.microsoft.com/en-us/azure/frontdoor/front-door-health-probes) (see warning).

@ryanhofdotgov Since the volume of probe entries has been flagged by ISO, I propose we decrease the frequency of health probes either as part of this issue or a follow on issue. Sound good?

**Comment by ryanhofdotgov** [comment]
I might see if resolving failed health checks is sufficient. Security teams are generally looking for things going wrong (HTTP 400), and probably have existing filters for things going correctly (HTTP 200).

Before decreasing from the default frequency of health probes, I'd want to articulate our expectations around instance failure, how long it takes to recover, etc. Right now the health probes are a little silly since we don't have multiple App Service instances to round-robin against, but that will change as we mature the system.
