### ISSUE TITLE
Spike: Evaluate work load of .NET 3.1 to .NET 5 migration

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#1231]
- Confirm support exists for App Service, Function Apps in US Government Cloud
- Test one web app, test one function app

**Comment by ryanhofdotgov** [comment]
In our engineering sync, the team thought it best to tackle this sooner rather than later, before we have post-production deployment concerns/priorities.

**Comment by timoballard** [comment]
@ryanhofdotgov -

Upgrading the web apps to .NET 5 is fairly trivial - no application code changes were required to upgrade the Dashboard. After updating the `TargetFramework` and `PackageReferences` in the project file, and making the necessary changes to the ARM template, the app continued to work as expected.

Upgrading the function apps is a bit more involved, because .NET 5 functions run [out of process](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide). This means that .NET 5 functions are decoupled from the Functions runtime and are essentially standalone console applications. This has numerous benefits, mostly as a result of exposing more fine-grained control over the application startup process, allowing for more idiomatic approaches to configuration, middleware and dependency injection.

After first attempting to move the Metrics API "in place" to .NET 5, I eventually threw in the towel and decided to create a .NET 5 function from scratch and copy over the application code from the .NET 3.1 version. In total, it took 1-2 hours to convert the Metrics API with the "start from scratch" approach.

I didn't (knowingly) make any unnecessary application-level changes, so [this branch](https://github.com/18F/piipan/compare/tdb/dashboard-net-5?expand=1) represents the minimum amount of work to get the `Dashboard <-> Metrics.Api`  functionality back to a working state on .NET 5. 

https://github.com/18F/piipan/compare/tdb/dashboard-net-5?expand=1

Note: tests currently fail on this branch due to package.lock inconsistencies across projects. - I didn't think it was worth the effort to untangle these for the purposes of this spike.

**Comment by ryanhofdotgov** [comment]
@timoballard Awesome. I think to wrap this spike up, we need to:
- [ ] Verify .NET 5 functions works in the government cloud ([GA in public cloud was March](https://azure.microsoft.com/en-us/updates/general-availability-azure-functions-supports-net-5-in-production/), gov is usually 2 months behind?). I can help you if you are still waiting on access.
- [ ] Add a new ADR saying we are choosing to migrate to .NET 5, update previous ADR to say it was superseded. (If you are using adr-tools, it's the -s option).
