### ISSUE TITLE
Write up ADR on disabling code coverage on app service start up code

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#1445]

**Comment by timoballard** [comment]
@ryanhofdotgov -

After some research and fiddling, I've changed my tune here a bit. It turns out to be fairly straightforward to verify that the service dependency graph is configured correctly by executing `ConfigureServices` and verifying that your DI container can build all of your top-level objects. In my experience, this is a worthwhile thing to do, especially as the service graph grows -- missing service registrations can easily go unnoticed until a particular code path is executed in a live environment, and even then you're sometimes left with an unhelpful exception trace.

Here's an example of this kind of test, using the Dashboard:

https://github.com/18F/piipan/blob/4a13532350451c41990fa8b6ac62360e3980d34d/dashboard/tests/Piipan.Dashboard.Tests/StartupTests.cs#L25

**Comment by ryanhofdotgov** [comment]
Excellent! I've added a strategy/documented approach for service registration testing to https://github.com/18F/piipan/issues/1558
