### ISSUE TITLE
Save match results for future reference

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#195]
Blocked by #452

When the NAC finds a likely case of duplicate participation, there will always be a need to share PII between states, including participant name, date of birth, and SSN.  States do not have an easy, reliable, and secure way to do this.

In order to avoid sharing PII, we envision generating a unique identifier for every positive match that can be shared in plaintext.  Eligibility workers would then log in to the NAC, enter the identifier, and then find the PII.

As a state eligibility worker, I want a secure place where I can look up a NAC match that was found by another state so that I can determine if the person is still enrolled in SNAP benefits in my state.

Look to #452 for considerations on generating the lookup ID

AC:
When matches are found by API or manual query:
- [ ] The match query is saved:
  - [ ] Name, DOB, SSN of participant at initiating state
  - [ ] Whether person is a vulnerable individual at initiating state
- [ ] The unique lookup ID (see #452) is saved
  

Related to #196 + #259 - Users have a way to look up previous NAC matches through FNS website + API, respectively

**Comment by juliaklindpaintner** [comment]
@cjhskippy Just to make it explicit/check my assumptions: 
- What is saved for the query and result is not necessarily what is displayed to the state agency user (research will inform what info is useful to them at query and ID lookup)
- I assume we are saving initiating state in order to track metrics. Have you thought of a reason why that data would be needed by the state agency workers? My only concern is that there is a way to distinguish a match result from a query by a state (which does not suggest existing duplicate participation) and a match result in the bulk match (which does suggest existing duplicate participation). I see you included "if any" so I'm assuming that in the bulk match this field would be empty or something? Τhat makes me wonder if there's any use in saving some data element that indicates which process a match was the result of? 
- I assume you are suggesting not saving DOB and SSN associated with the match result because those have to be exact matches? Any reason we would want to build for a future scenario where there might be some fuzziness allowed?
- I assume the above describes the bare minimum that should be saved. As additional optional elements are identified, those could be added (since we have heard that information about dates of eligibility, case status, etc may be useful).

**Comment by cjhskippy** [comment]
1. (query result != what the SA worker sees) - agree!
2. Initiating state would probably not just be for metrics.  I would imagine that playing in to access controls - only workers at the states involved in a match would have permission to look up PII.  Also yes to the metrics use case.  Good call re: differentiating between reasons for initiating the match.  I do think we'll need to do that (issue #462 now) but I think we can defer it for now.
3. Exactly right - we don't need to save them in the immediately foreseeable future, but if we ever let those become fuzzy matches, we'll need to start saving them and including them in match lookup API results.
4. Also yes.  Made #463 for the case status and last benefit date.
