### ISSUE TITLE
Look up NAC match via website

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#196]
As a state eligibility worker, I want a secure place where I can look up a NAC match that was found by another state so that I can determine if the person is still enrolled in SNAP benefits in my state.

AC:
- [ ] Available in same website where eligibility workers can query the NAC
- [ ] Users can enter the unique lookup ID and get:
   - [ ] Name, DOB, SSN of the participant or applicant at the initiating state
   - [ ] Other states involved in the match, if any
     - [ ] The name used at the other states
- [ ] If lookup ID is not valid, provide error message (something like "no records exist for match code X").

**Comment by juliaklindpaintner** [comment]
@cjhskippy Upon reflection during wireframing, I'm not sure it makes sense to display 'initiating state' in the results of a Match ID. Theoretically, a search could be conducted by multiple states over the course of time. If a match file is specific to an individual, rather than to an inquiry, the "initiating state" could change. Based on this user story, the information a user is looking for in searching by Match ID is simply the PII that allows them to look them up in their eligibility system. I agree it should show any state(s) in which the individual is currently enrolled, but perhaps this is not framed as "matching state." Happy to discuss/elaborate!

**Comment by cjhskippy** [comment]
Ooh, I think this will make for good discussion.  In my head, I was envisioning one match file per person per case action (application, recertification, addition of a household member).  The match would be resolved alongside that case action and would not persist to other times when the same individual is involved in another potential match.
