### ISSUE TITLE
Implement rate limiting on the Query Tool's search form

### ISSUE THREAD

**Issue by edwintorres** [18F/piipan#2345]
For set the API Rate Limit, we need a way to match the valid request, it could be a query string variable o header variable. Right now the API Rate Limit is using the URL to match the request but the URL is going to change in production enviroment.

**Comment by kingcomma** [comment]
Expanding the scope of this issue to include rate limiting on the Query Tool's duplicate participation search form. See #2327 for initial research into this approach.

Updated AC: 

- [ ] Query Tool search form is rate limited
  - [ ] Rate limiting is implemented as a custom rule on the Query Tool's WAF that matches `POST` requests from the search form
  - [ ] Custom rule is configured via IaC and re-runnable without error (see https://github.com/18F/piipan/pull/2327#issuecomment-992986691)

This issue was separated off from #2301.
