### ISSUE TITLE
Allow states to query for households in one API call

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#368]
As a state system integrator, I want to be able to submit multiple PII records in one query to the NAC. This would allow me to more easily process entire households without having to perform multiple web service API calls.

Implementation notes:
* small-scale, household level "bulk" queries for near-real time responses (max household size should be further researched, but likely maxes around 50.  )

AC:
- [ ] Queries can accept up to 50 PII records (our estimate for a maximally-large household)
- [ ] Query responses include the results for every person in the query
- [ ] (optional) Measure and report on a typical response time for queries with 50 PII records

Issue was originally paired with #865 (support overnight processing of recertifications in a single API call)

**Comment by ryanhofdotgov** [comment]
Needs to be split up

**Comment by cjhskippy** [comment]
Spun off additional issue of #865 (batch queries for the purpose of overnight recertifications)

**Comment by echappen** [comment]
> Query responses include the results for every person in the query

Does this mean:
1. There's a list of matches for every person in the query?
1. There's a Lookup ID for every person in the query?

cc @ryanhofdotgov @cjhskippy

**Comment by echappen** [comment]
And by "person" I mean for each unique PII object in the query

**Comment by kingcomma** [comment]
Conceptually, I had been thinking of this as the same approach we currently take with the only difference being the orchestrator running multiple match queries rather than a single query. In that case, the orchestrator would return an array of match response objects (each with their own `lookup_id` and `matches` properties).

I've also been wondering if we should just default to accepting an array for both requests and responses, whether the request contains a single applicant or multiple household members? The trade off there is a bigger "break" but perhaps a better experience if state systems don't have to conditionally check for an object or an array.

**Comment by ryanhofdotgov** [comment]
+1 to breaking things now and using an array for both query and response to reduce variations in how the API is used.

**Comment by ryanhofdotgov** [comment]
@echappen I would do this work in 2 steps – update the spec, give us an opportunity to look at it for a day or two, then do the implementation work.
