### ISSUE TITLE
Generate unique lookup ID in Orchestrator API

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#452]
As a State Agency worker, I want to be able to share PII with another state agency securely, with as little data entry and memorization as possible so that I can process cases faster.

- As we currently conceive it, State agency workers will share PII by providing a unique Lookup ID to each other
- Only authorized personnel will have access to get PII from Lookup IDs - there isn't a strong need to make it hard to guess valid Lookup IDs
- The Lookup ID will be manually typed into emails and state agency systems.  In order to make this easy and avoid problems caused by typos, the unique identifier should:
  - be as short as we can reasonably make it
  - Use easily-typed characters (recommend case-insensitive alphabet + numbers)
  - Be displayed in the most easily-recognized way (recommend saving letters IN CAPS so the default is to display them that way by state agency systems too)
  - avoid the chances of Lookup IDs that are different by only one character - these increase the chances of a typo causing an agency to look up the wrong case information.
  - avoid characters that look identical at a glance (0/O and 1/I)
  - avoid including offensive words in our random strings
- Assuming we save up to 3 years of matches, 1% of queries result in a match, 40m participants overall, and queries aren't repeated for the same case, a name space of 12 million possibilities should be good enough. 6 character strings using 29 possible choices for each character (~600m possibilities) should be sufficient.

Closely related to #195 

AC:
- [x] Lookup IDs must be unique
- [x] Lookup IDs should not be sequential
- [x] Lookup IDs can include any capital letters except for vowels and any numbers except for 0 and 1 (exclude A,E,I,O,U,0,1)
- [x] Lookup IDs are six digits in length
- [x] When a match is returned by the Orchestrator API, the NAC should generate a new Lookup IDs and include the Lookup ID in its response.

**Comment by juliaklindpaintner** [comment]
@cjhskippy I haven't solved for this problem before but after a brief amount of research on user-friendly alphanumeric codes here are my two cents (and I imagine none of this will be news to our engineers): 
- A common rule of thumb is that people can keep 7 characters in their mind +/-2, so 5 characters seems good, but I think up to 7 would be okay
- Definitely agree on case-INsensitive and no special characters (so base 36, which I think is how you got the ~60million permutations)
- Consider removing characters that can be ambiguous depending on the font, especially since we don't control that in state systems (0/O, 1/I) --> That would be base 32 for ~33million combinations in a 5 character string
- Consider grouping like characters for a more predictable format, e.g. 3 numbers followed by 3 letters. This constrains the permutations significantly, though.
- Consider the accidental generation of offensive words — there may be a way to filter for this? Perhaps less of a concern since it's not fully public-facing, but might be good to avoid. (one source I read suggested removing vowels to achieve this, but that may not be sufficient)
- It occurred to me that we could consider adding an identifying element to them if that would be of any use, e.g., a 5 digit random string followed by the 2 letter state abbreviation of the initiating state? Not sure if that would be useful for metrics, but I was thinking it could help users distinguish between inquiries more easily? 
- [A different approach I came across](https://stackoverflow.com/questions/34708/how-can-i-generate-a-unique-small-random-and-user-friendly-key) was to create random combinations of short recognizable words to aid in user-friendliness (e.g., CAT892HAT. That might make it easier to remember the match ID and they could be longer, but my gut is that this is somewhat unnecessary/risky if we want to make sure all the combinations are inoffensive.
- [Another approach is to use "proquints"](https://stackoverflow.com/questions/36392404/generate-short-unique-identifiers) which are PROnouncable QUINTuplet of alternating unambiguous consonants and vowels, but that would make it pretty hard to get enough unique combinations unless we added a few more numbers to the end.

**Comment by cjhskippy** [comment]
This is GREAT, thank you @juliaklindpaintner!  I'm biased toward simplicity for now, so I'd like to dodge (word / number generation that also filters out offensive words and reaches enough permutations).  I do also think your inclination to avoid ambiguous characters and offensive words is right.  If we take out I and O, we're already well on our way to pulling all the vowels, so maybe we just drop [A, E, I, O, U, 0, 1] for 29 characters.   I think we jump to 6 characters for ~600m possibilities.

I'd recommend observing interaction with the above rather simple baseline and considering things like word inclusion / adding the initiating state as optimizations that we keep on the table, but bake in later.

**Comment by kingcomma** [comment]
Re-opening. Unintentionally closed by mis-typing the reference in #620.
