### ISSUE TITLE
Extend the spec for the Orchestrator API to include match ID

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#481]
Precursor to #452 

- Update documented spec for the Orchestrator API to return a match ID.

**Comment by echappen** [comment]
@cjhskippy Was this for the query endpoint to return a Match ID _instead_ of the Pii Records, or in addition to a Pii Record?

In other words, returning something like this for a match query:

<img width="324" alt="Screen Shot 2021-03-16 at 11 25 43 AM" src="https://user-images.githubusercontent.com/4267629/111344609-8317a980-864a-11eb-8a10-b9fefe8d08fc.png">

Instead of this:

<img width="337" alt="Screen Shot 2021-03-16 at 11 23 16 AM" src="https://user-images.githubusercontent.com/4267629/111344651-8dd23e80-864a-11eb-9e56-fcddd125968e.png">

**Comment by ryanhofdotgov** [comment]
@echappen the match id would be in addition to the existing Pii record data in the response.

**Comment by echappen** [comment]
@ryanhofdotgov Thanks, so each Pii Record would have 1 Match ID like this?

<img width="297" alt="Screen Shot 2021-03-16 at 1 24 14 PM" src="https://user-images.githubusercontent.com/4267629/111360625-f9240c80-865a-11eb-897a-9a63df2f98fe.png">

**Comment by ryanhofdotgov** [comment]
Almost – the match id encapsulates the input of the query, so it is a top-level property, rather than associated with each and every PII record. If there's a match there's most likely only one other state, but there could be several and we wouldn't repeat the match id on each.

**Comment by kingcomma** [comment]
Is there a scenario where the match ID would still be part of the PII record, even if it's shared across multiple? I'm probably getting ahead of myself, but thinking of a scenario where the orchestrator API is extended to support batch/bulk querying (#368).

**Comment by ryanhofdotgov** [comment]
Without looking at the schema, I would say that the match ID is 1:1 to search tuples (fn,mn,ls,dob,ssn) that have matches. In a bulk scenario, I submit a search for 10 tuples, and 3 have matches, I'm going to get 3 match ids across my response.
