### ISSUE TITLE
Clarify how to share vulnerability status in bulk uploads

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#850]
As a state agency IT worker, I want clear guidance to specify an individual's status as vulnerable so that I know how to send information to the NAC.  I also want the data to be stored in a standard way across all states so that I know how to make sense of data that other states uploaded.

We are defining "vulnerable" as a person who would be put at risk by having their location information exposed.

AC:
- [ ] Create a "protect location" field that will accept an individual's vulnerability status
- [ ] Include yes/no/unknown options
- [ ] "Protect location" field is optional - if a row is missing that field, the upload is still accepted
- [ ] Update documentation with guidance on the "Protect location" field (but note that final rule is still pending)

**Comment by echappen** [comment]
@ryanhofdotgov @cjhskippy Did we land on whether the "yes/no/unknown" field will be represented as boolean + null (null being unknown), or as a non-nullable enum of strings: `["yes", "no", "unknown"]`

**Comment by ryanhofdotgov** [comment]
Because the field has been decided to be optional, the enum doesn't save us from handling the explicitly null or unspecified case. 

How about:
- CSV bulk import format: true, false, or empty string (related to https://github.com/18F/piipan/issues/939, string fields should be white spaced trimmed before evaluation)
- Database column: boolean (can be null)
- JSON API response: boolean (can have value of null, or equivalently, the property is not specified at all)
- Display values in the query tool: map null or unspecified property to "Unknown", map true to "Yes" and false to "No"?

**Comment by ryanhofdotgov** [comment]
Also add that for CSV bulk import format, since it's optional, the column may not be present in the CSV file at all, which is roughly equivalent to the JSON scenario where the property is not specified at all.

**Comment by cjhskippy** [comment]
For the JSON API response, I think it can make sense to return null/empty for unknown, but we should provide guidance to treat those responses identically to yes responses.

For the display values in the query tool, I think it's more usable to map null or unspecified to "Yes" instead of "Unknown".  It seems like the same amount of work for us, but it will save workers the cognitive load of having to remember what to do with "Unknown"

**Comment by cjhskippy** [comment]
Also: Added the related issue for the match API to the stretch goals for this sprint (#989).  I was assuming that incorporating these changes into the FNS website (#851) would be something we tackle in future sprints.  Copied the notes from this comment thread into both issues.
